#!/bin/bash

# Don't forget to update '/etc/anacrontab' after changing path!
LOG=/var/log/trim.log
DEVS="/ /home"

sudo sh -c "echo '*** $(date -R) ***' >> $LOG"
for i in $DEVS
do
 sudo sh -c "fstrim -v $i >> $LOG"
done
